window:
  startup_mode: Maximized
  padding:
    x: 10 
    y: 25 

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

live_config_reload: true

scrolling:
  history: 10000

shell: 
  program: /usr/local/bin/tmux

font: 
  size: 14

colors:
  # Default colors
  primary:
    background: '0x1b2b34'
    foreground: '0xd8dee9'

  # Normal colors
  normal:
    black:   '0x29414f'
    red:     '0xec5f67'
    green:   '0x99c794'
    yellow:  '0xfac863'
    blue:    '0x6699cc'
    magenta: '0xc594c5'
    cyan:    '0x5fb3b3'
    white:   '0x65737e'

  # Bright colors
  bright:
    black:   '0x405860'
    red:     '0xec5f67'
    green:   '0x99c794'
    yellow:  '0xfac863'
    blue:    '0x6699cc'
    magenta: '0xc594c5'
    cyan:    '0x5fb3b3'
    white:   '0xadb5c0'

bell:
  animation: EaseOutExpo
  color: "0xffffff"
  duration: 0

mouse:
  hide_when_typing: true

cursor:
  style: Block
  unfocused_hollow: true

key_bindings:
  - {key: A, mods: Command, chars: "\x01"}
  - {key: B, mods: Command, chars: "\x02"}
  - {key: C, mods: Command, chars: "\x03"}
  - {key: D, mods: Command, chars: "\x04"}
  - {key: E, mods: Command, chars: "\x05"}
  - {key: F, mods: Command, chars: "\x06"}
  - {key: G, mods: Command, chars: "\x07"}
  - {key: H, mods: Command, chars: "\x08"}
  - {key: I, mods: Command, chars: "\x09"}
  - {key: J, mods: Command, chars: "\x0a"}
  - {key: K, mods: Command, chars: "\x0b"}
  - {key: L, mods: Command, chars: "\x0c"}
  - {key: M, mods: Command, chars: "\x0d"}
  - {key: N, mods: Command, chars: "\x0e"}
  - {key: O, mods: Command, chars: "\x0f"}
  - {key: P, mods: Command, chars: "\x10"}
  - {key: Q, mods: Command, chars: "\x11"}
  - {key: R, mods: Command, chars: "\x12"}
  - {key: S, mods: Command, chars: "\x13"}
  - {key: T, mods: Command, chars: "\x14"}
  - {key: U, mods: Command, chars: "\x15"}
  - {key: V, mods: Command, chars: "\x16"}
  - {key: W, mods: Command, chars: "\x17"}
  - {key: X, mods: Command, chars: "\x18"}
  - {key: Y, mods: Command, chars: "\x19"}
  - {key: Z, mods: Command, chars: "\x1a"}
