
window:
  startup_mode: Maximized
  decorations: None 
  padding:
    x: 10 
    y: 25 

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

live_config_reload: true

scrolling:
  history: 10000

colors:
  primary:
    background: "#282828"
    foreground: "#ebdbb2"

  normal:
    black: "#282828"
    red: "#cc241d"
    green: "#98971a"
    yellow: "#d79921"
    blue: "#458588"
    magenta: "#b16286"
    cyan: "#689d6a"
    white: "#a89984"

  bright:
    black: "#928374"
    red: "#fb4934"
    green: "#b8bb26"
    yellow: "#fabd2f"
    blue: "#83a598"
    magenta: "#d3869b"
    cyan: "#8ec07c"
    white: "#ebdbb2"

bell:
  animation: EaseOutExpo
  color: "0xffffff"
  duration: 0

shell:
  program: /usr/bin/tmux  

mouse:
  hide_when_typing: true

cursor:
  style: Block
  unfocused_hollow: true
